//@ts-ignore
import type { Metadata } from "next";
import "@/app/global.css";
import React from "react";
import ScrollThumbEffect from "./Scrollbar";

export const metadata: Metadata = {
  title: "NSS IIIT-H",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>{`
          /* Hide scrollbars for all elements */
          html, body, * {
            scrollbar-width: none !important; /* Firefox */
            -ms-overflow-style: none !important; /* IE 10+ */
          }
          ::-webkit-scrollbar {
            display: none !important; /* Chrome, Safari, Opera */
          }
        `}</style>
        {/* Google Fonts: Roboto */}
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ margin: 0, padding: 0, overflowX: "hidden", fontFamily: "'Roboto', Arial, sans-serif" }}>
        <ScrollThumbEffect />
        {children}
      </body>
    </html>
  );
}
