global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'backend-api'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-1:8000', 'backend-2:8000']
    scrape_timeout: 5s

  # Frontend health checks
  - job_name: 'frontend'
    scrape_interval: 30s
    metrics_path: '/api/health'
    static_configs:
      - targets: ['frontend-1:3000', 'frontend-2:3000']
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx:9113']
    scrape_timeout: 5s

  # MongoDB metrics (if mongodb-exporter is added)
  - job_name: 'mongodb'
    scrape_interval: 30s
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_timeout: 10s

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_timeout: 10s

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_timeout: 10s
